# Список доступных реакций
REACTIONS = [
    "👍", # (Thumbs Up)
    "❤️", #  (Heart)
    "🔥", #  (Fire)
    "💯", #  (100)
    "😎", #  (Cool)
    "🎉", #  (Party)
    # "😂", #  (Laughing)
    "😍", # (Heart Eyes)
    "😢", # (Crying)
    "👏", # (Clapping)
    "👀", # (Eyes)
    "😡", # (Angry)
    "🙏", # (Praying)
    "🤔", # (Thinking)
    "😭", # (Sob)
    "🤗", # (Hugging)
    "😱", # (Screaming)
    # "💪", # (Flexed Biceps)
    "💔", # (Broken Heart)
    # "🎶", # (Music Notes)
    # "🌟", # (Star)
    # "🎁", # (Gift)
    # "🥳", # (Celebrating)
    "🤩", # (Star-Struck)
    "🤯", # (Exploding Head)
    # "🥺", # (Pleading Face)
    # "😅", # (Sweat Smile)
    # "🤤", # (Drooling)
    "🤪", # (Zany Face)
    "😇", # (Smiling Face with Halo)
    # "😏", # (Smirking Face)
    # "😬", # (Grimacing Face)
    "🥰", # (Smiling Face with Hearts)
    # "🥺", # (Pleading Face)
    # "🤒", # (Face with Thermometer)
    # "😷", # (Face with Medical Mask)
    # "🤕", # (Face with Head-Bandage)
    # "🤧", # (Sneezing Face)
    # "🥳", # (Partying Face)
    "🤮", # (Face Vomiting)
    "🥴", # (Woozy Face)
    # "🤑", # (Money-Mouth Face)
    # "🤠", # (Cowboy Hat Face)
    "😈", # (Smiling Face with Horns)
    # "👿", # (Angry Face with Horns)
    # "👹", # (Ogre)
    # "👺", # (Goblin)
    "💩" # (Pile of Poo)
    ]

# Исключаемые реакции (например, если не хотите использовать определенные реакции)
EXCLUDED_REACTIONS = [""]

# Фильтруем реакции, исключая нежелательные
AVAILABLE_REACTIONS = [reaction for reaction in REACTIONS if reaction not in EXCLUDED_REACTIONS]
